### ISSUE TITLE
Angular Nativescript "EmojiPicker" and "EmojiLabel" makes error on page

### ISSUE THREAD

**Issue by SergioZhydecky** [hrueger/nativescript-emoji-picker#1]
Hi. 
When I add 

```
	<EmojiPicker row="0" #myEmojiPicker></EmojiPicker>
			<Button row="1" text="Toggle Popup" (tap)="onButtonTap()" class="btn btn-primary btn-active"></Button>
			<EmojiLabel #myEmojiLabel row="2" text="Have fun with the nativescript-emoji-picker😃"></EmojiLabel>
			<Button row="3" text="Copy text to label" (tap)="onCopyBtnTap()" class="btn btn-primary btn-active"></Button>
```
to view, I get issue: 
CONSOLE ERROR file:///node_modules/@angular/core/fesm5/core.js:5847:0 ERROR Error: Uncaught (in promise): TypeError: undefined is not a constructor (evaluating 'new viewClass()')
createView@file:///node_modules/nativescript-angular/view-util.js:215:0
createElement@file:///node_modules/nativescript-angular/renderer.js:138:0
createElement@file:///node_modules/nativescript-angular/renderer.js:415:0
createElement@file:///node_modules/@angular/core/fesm5/core.js:28475:0
createElement@file:///node_modules/@angular/core/fesm5/core.js:26511:0
createViewNodes@file:///node_modules/@angular/core/fesm5/core.js:27450:0
callViewAction@file:///node_modules/@angular/core/fesm5/core.js:27805:0
execComponentViewsAction@file:///node_modules/@angular/core/fesm5/core.js:27724:0
createViewNodes@file:///node_modules/@angular/core/fesm5/core.js:27517:0
createRootView@file:///node_modules/@angular/core/fesm5/core.js:27403:0
callWithDebugContext@file:///node_modules/@angular/core/fesm5/core.js:28411:0
create@file:///node_modules/@angular/core/fesm5/core.js:18750:0
createComponent@file:///node_modules/@angular/core/fesm5/core.js:18861:0
loadWithFactory@file:///node_modules/nativescript-angular/common/detached-loader.js:38:0
activateOnGoForward@file:///node_modules/nativescript-angular/router/page-router-outlet.js:283:0
activateWith@file:///node_modules/nativescript-angular/router/page-router-outlet.js:261:0
activateRoutes@file:///node_modules/@angular/router/fesm5/router.js:2315:0
file:///node_modules/@angular/router/fesm5/router.js:2266:0
forEach@[native code]
activateChil<…>

(ts part also added exactly same as in demo, and module is imported)

The same issue/error in demo-angular application

node v10
nativescript v6
angular v8

**Comment by hrueger** [comment]
Hi,
are you using IOS or Android?
At the moment, the plugin works only in Android as I couldn't find a native library which provides an emoji picker. I forgot to add this to the readme.

**Comment by SergioZhydecky** [comment]
Yes, we are trying to use this picker. I have built it on android today and cant see smile picker. Could you send some screen shot how does it look like? And are you going to get ios version to work in near feature ?

**Comment by SergioZhydecky** [comment]
for me it looks like this and toggle popup button does not work
<img width="313" alt="image" src="https://user-images.githubusercontent.com/6481741/65325934-e1301180-dbb8-11e9-9c09-2d9595c32bef.png">

**Comment by hrueger** [comment]
I'll try to make this plugin work on IOS as soon as I can.
I also added screenshots to the readme as you requested.

Are you sure that the `onButtonTap` method here
```html
<Button row="1" text="Toggle Popup" (tap)="onButtonTap()" class="btn btn-primary btn-active"></Button>
```
is actually called?
You can check this for example by adding a `console.log("Method called!");` line to the top of this method. 
If this works, can you `console.log(this.myEmojiPicker)` to the console and see if it is undefined?

**Comment by SergioZhydecky** [comment]
Hi, sorry for long time answering, I was switched to another urgent tasks. I got to work plugin on android, I can see picker, toggle button works. It was my mistake, I commented out some line when played with that on IOS. But I still need ios target. Hope you will be able to fix iso soon!Thank you!

**Comment by hrueger** [comment]
Hi,
I'm glad that you resolved your issue.
I'm very sorry that I cannot provide an IOS version soon. I simply don't know much about IOS developement and it is not easy to do without a Mac.
But feel free to fork this repo and implement this by yourself. It shouldn't be too complicated with https://github.com/isaced/ISEmojiView
I would be very happy about a pull request!
