### ISSUE TITLE
ios release

### ISSUE THREAD

**Issue by NaBo1985** [hrueger/nativescript-emoji-picker#41]
I noticed you said that the ios version is a work in progress... I was wondering when it might be done?

**Comment by hrueger** [comment]
@NaBo1985 Sorry, I forgot to remove it. I tried making an iOS version some time ago but it didn't work. The problem is that I don't have a MacOS device and developing in a virtualbox is simply not possible.

However, I'd be happy to review and eventually merge a PR ;-)

**Comment by NaBo1985** [comment]
I see to bad thanx for your attempt
